import { Data2 } from '../interfaces/RedditResponse';

export const mockedRedditResponse: Array<Data2> = [
  {
    approved_at_utc: null,
    subreddit: 'ACNHTurnips',
    selftext: '',
    author_fullname: 't2_2nxnnf4r',
    saved: false,
    mod_reason_title: null,
    gilded: 0,
    clicked: false,
    title: '[Nooks] selling for 471 bells; pls comment first and then dm for dodo',
    link_flair_richtext: [],
    subreddit_name_prefixed: 'r/ACNHTurnips',
    hidden: false,
    pwls: 6,
    link_flair_css_class: '',
    downs: 0,
    thumbnail_height: 105,
    top_awarded_type: null,
    hide_score: false,
    name: 't3_ta7wt3',
    quarantine: false,
    link_flair_text_color: 'light',
    upvote_ratio: 0.96,
    author_flair_background_color: null,
    ups: 26,
    total_awards_received: 1,
    media_embed: {},
    thumbnail_width: 140,
    author_flair_template_id: null,
    is_original_content: false,
    user_reports: [],
    secure_media: null,
    is_reddit_media_domain: true,
    is_meta: false,
    category: null,
    secure_media_embed: {},
    link_flair_text: 'Ended',
    can_mod_post: false,
    score: 26,
    approved_by: null,
    is_created_from_ads_ui: false,
    author_premium: false,
    thumbnail: 'https://a.thumbs.redditmedia.com/LpvJ4aBlyIvmkCLMkh95Pn6LGcsSVYCEcyDBumdf8x4.jpg',
    edited: false,
    author_flair_css_class: null,
    author_flair_richtext: [],
    gildings: {},
    post_hint: 'image',
    content_categories: null,
    is_self: false,
    subreddit_type: 'public',
    created: 1646832927,
    link_flair_type: 'text',
    wls: 6,
    removed_by_category: null,
    banned_by: null,
    author_flair_type: 'text',
    domain: 'i.redd.it',
    allow_live_comments: false,
    selftext_html: null,
    likes: null,
    suggested_sort: null,
    banned_at_utc: null,
    url_overridden_by_dest: 'https://i.redd.it/ugmtnv1a2dm81.jpg',
    view_count: null,
    archived: false,
    no_follow: false,
    is_crosspostable: false,
    pinned: false,
    over_18: false,
    preview: {
      images: [
        {
          source: {
            url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?auto=webp&amp;s=cc9727b8a679cd8054120b268d4fd7b33303afa0',
            width: 4032,
            height: 3024,
          },
          resolutions: [
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c2feab921e9dc0f29eac62b7890af1cec6ecf988',
              width: 108,
              height: 81,
            },
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=70c5dd3cc5862d93834bc146ca981e78503c2b91',
              width: 216,
              height: 162,
            },
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=28e1f4d36f12fc883b6086c8a1bb39a550c37003',
              width: 320,
              height: 240,
            },
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=8005fcb41c105ea869ec89eb648acc9c7f8c126d',
              width: 640,
              height: 480,
            },
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=4151f41b32f51dd3a376b16b68b499158236e882',
              width: 960,
              height: 720,
            },
            {
              url: 'https://preview.redd.it/ugmtnv1a2dm81.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=a28bcea5dfbdafb4deeea8faf75b460588b3bad0',
              width: 1080,
              height: 810,
            },
          ],
          variants: {},
          id: 'xUSp9Uhwlcn3RKip9jxihMd3j-CClfCH8ZPl-gRwq8w',
        },
      ],
      enabled: true,
    },
    all_awardings: [
      {
        giver_coin_reward: null,
        subreddit_id: null,
        is_new: false,
        days_of_drip_extension: 0,
        coin_price: 125,
        id: 'award_5f123e3d-4f48-42f4-9c11-e98b566d5897',
        penny_donate: null,
        award_sub_type: 'GLOBAL',
        coin_reward: 0,
        icon_url: 'https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png',
        days_of_premium: 0,
        tiers_by_required_awardings: null,
        resized_icons: [
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0',
            width: 16,
            height: 16,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef',
            width: 32,
            height: 32,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63',
            width: 48,
            height: 48,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb',
            width: 64,
            height: 64,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b',
            width: 128,
            height: 128,
          },
        ],
        icon_width: 2048,
        static_icon_width: 2048,
        start_date: null,
        is_enabled: true,
        awardings_required_to_grant_benefits: null,
        description: 'When you come across a feel-good thing.',
        end_date: null,
        subreddit_coin_reward: 0,
        count: 1,
        static_icon_height: 2048,
        name: 'Wholesome',
        resized_static_icons: [
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0',
            width: 16,
            height: 16,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef',
            width: 32,
            height: 32,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63',
            width: 48,
            height: 48,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb',
            width: 64,
            height: 64,
          },
          {
            url: 'https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b',
            width: 128,
            height: 128,
          },
        ],
        icon_format: null,
        icon_height: 2048,
        penny_price: null,
        award_type: 'global',
        static_icon_url: 'https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png',
      },
    ],
    awarders: [],
    media_only: false,
    link_flair_template_id: 'aa7c035e-72c8-11ea-af84-0eea56f6d1f7',
    can_gild: false,
    spoiler: false,
    locked: false,
    author_flair_text: null,
    treatment_tags: [],
    visited: false,
    removed_by: null,
    mod_note: null,
    distinguished: null,
    subreddit_id: 't5_2fvwbs',
    author_is_blocked: false,
    mod_reason_by: null,
    num_reports: null,
    removal_reason: null,
    link_flair_background_color: '#ea0027',
    id: 'ta7wt3',
    is_robot_indexable: true,
    report_reasons: null,
    author: 'saurehefexyz',
    discussion_type: null,
    num_comments: 24,
    send_replies: true,
    whitelist_status: 'all_ads',
    contest_mode: false,
    mod_reports: [],
    author_patreon_flair: false,
    author_flair_text_color: null,
    permalink: '/r/ACNHTurnips/comments/ta7wt3/nooks_selling_for_471_bells_pls_comment_first_and/',
    parent_whitelist_status: 'all_ads',
    stickied: false,
    url: 'https://i.redd.it/ugmtnv1a2dm81.jpg',
    subreddit_subscribers: 50205,
    created_utc: 1646832927,
    num_crossposts: 0,
    media: null,
    is_video: false,
  },
  {
    approved_at_utc: null,
    subreddit: 'ACNHTurnips',
    selftext: '',
    author_fullname: 't2_7fozsupk',
    saved: false,
    mod_reason_title: null,
    gilded: 0,
    clicked: false,
    title: '[NOOKS] Nooklings buying for 454. Open until 11PM est, DM for Dodo code',
    link_flair_richtext: [],
    subreddit_name_prefixed: 'r/ACNHTurnips',
    hidden: false,
    pwls: 6,
    link_flair_css_class: '',
    downs: 0,
    thumbnail_height: 140,
    top_awarded_type: null,
    hide_score: false,
    name: 't3_t6vgl0',
    quarantine: false,
    link_flair_text_color: 'light',
    upvote_ratio: 1,
    author_flair_background_color: null,
    ups: 18,
    total_awards_received: 0,
    media_embed: {},
    thumbnail_width: 140,
    author_flair_template_id: null,
    is_original_content: false,
    user_reports: [],
    secure_media: null,
    is_reddit_media_domain: true,
    is_meta: false,
    category: null,
    secure_media_embed: {},
    link_flair_text: 'Ended',
    can_mod_post: false,
    score: 18,
    approved_by: null,
    is_created_from_ads_ui: false,
    author_premium: false,
    thumbnail: 'https://b.thumbs.redditmedia.com/6nuY2VbndNmktJtI3HHOsb9DRr8YDGpQtsLrVzOKiho.jpg',
    edited: false,
    author_flair_css_class: null,
    author_flair_richtext: [],
    gildings: {},
    post_hint: 'image',
    content_categories: null,
    is_self: false,
    subreddit_type: 'public',
    created: 1646435064,
    link_flair_type: 'text',
    wls: 6,
    removed_by_category: null,
    banned_by: null,
    author_flair_type: 'text',
    domain: 'i.redd.it',
    allow_live_comments: false,
    selftext_html: null,
    likes: null,
    suggested_sort: null,
    banned_at_utc: null,
    url_overridden_by_dest: 'https://i.redd.it/1er1ah587gl81.jpg',
    view_count: null,
    archived: false,
    no_follow: false,
    is_crosspostable: false,
    pinned: false,
    over_18: false,
    preview: {
      images: [
        {
          source: {
            url: 'https://preview.redd.it/1er1ah587gl81.jpg?auto=webp&amp;s=b09363f6cfa8884dbed6bff4f290376293d05567',
            width: 3024,
            height: 4032,
          },
          resolutions: [
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=74459829a5788776a33631550033ea58ad711aae',
              width: 108,
              height: 144,
            },
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=2174e3d0553337a24ad4cf6066da7fbaa5f2ec53',
              width: 216,
              height: 288,
            },
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=1133699bafbe85106ca11d6ded905b9ad1a0e9b7',
              width: 320,
              height: 426,
            },
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=c448e54903616e86e7eea98ddcd424fdbe2d0a39',
              width: 640,
              height: 853,
            },
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=1b3f1006e58f1a3de005fe0ab83f719bae08cb58',
              width: 960,
              height: 1280,
            },
            {
              url: 'https://preview.redd.it/1er1ah587gl81.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=70f4ac66d2fd2201a0ec85d6c6ce1ef3e9fada0b',
              width: 1080,
              height: 1440,
            },
          ],
          variants: {},
          id: 'BGCXDYipk-4JdRgZJ8jHpqL8GiPlG1MMGF8lGNmmE4Q',
        },
      ],
      enabled: true,
    },
    all_awardings: [],
    awarders: [],
    media_only: false,
    link_flair_template_id: 'aa7c035e-72c8-11ea-af84-0eea56f6d1f7',
    can_gild: false,
    spoiler: false,
    locked: false,
    author_flair_text: null,
    treatment_tags: [],
    visited: false,
    removed_by: null,
    mod_note: null,
    distinguished: null,
    subreddit_id: 't5_2fvwbs',
    author_is_blocked: false,
    mod_reason_by: null,
    num_reports: null,
    removal_reason: null,
    link_flair_background_color: '#ea0027',
    id: 't6vgl0',
    is_robot_indexable: true,
    report_reasons: null,
    author: 'makethosebells',
    discussion_type: null,
    num_comments: 12,
    send_replies: true,
    whitelist_status: 'all_ads',
    contest_mode: false,
    mod_reports: [],
    author_patreon_flair: false,
    author_flair_text_color: null,
    permalink: '/r/ACNHTurnips/comments/t6vgl0/nooks_nooklings_buying_for_454_open_until_11pm/',
    parent_whitelist_status: 'all_ads',
    stickied: false,
    url: 'https://i.redd.it/1er1ah587gl81.jpg',
    subreddit_subscribers: 50205,
    created_utc: 1646435064,
    num_crossposts: 0,
    media: null,
    is_video: false,
  },
  {
    approved_at_utc: null,
    subreddit: 'ACNHTurnips',
    selftext:
      'Just 1.5h hours left before the shop changes.\nTips not needed, but would love if someone could bring me a peach or pear so I have all fruits 😀',
    author_fullname: 't2_jo7tyf4',
    saved: false,
    mod_reason_title: null,
    gilded: 0,
    clicked: false,
    title: '[Nooks] selling for 600! DM for code',
    link_flair_richtext: [],
    subreddit_name_prefixed: 'r/ACNHTurnips',
    hidden: false,
    pwls: 6,
    link_flair_css_class: '',
    downs: 0,
    thumbnail_height: null,
    top_awarded_type: null,
    hide_score: false,
    name: 't3_ta4829',
    quarantine: false,
    link_flair_text_color: 'light',
    upvote_ratio: 1,
    author_flair_background_color: null,
    subreddit_type: 'public',
    ups: 10,
    total_awards_received: 0,
    media_embed: {},
    thumbnail_width: null,
    author_flair_template_id: null,
    is_original_content: false,
    user_reports: [],
    secure_media: null,
    is_reddit_media_domain: false,
    is_meta: false,
    category: null,
    secure_media_embed: {},
    link_flair_text: 'Hosting Nooks',
    can_mod_post: false,
    score: 10,
    approved_by: null,
    is_created_from_ads_ui: false,
    author_premium: false,
    thumbnail: 'self',
    edited: false,
    author_flair_css_class: null,
    author_flair_richtext: [],
    gildings: {},
    content_categories: null,
    is_self: true,
    mod_note: null,
    created: 1646818545,
    link_flair_type: 'text',
    wls: 6,
    removed_by_category: null,
    banned_by: null,
    author_flair_type: 'text',
    domain: 'self.ACNHTurnips',
    allow_live_comments: true,
    selftext_html:
      '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Just 1.5h hours left before the shop changes.\nTips not needed, but would love if someone could bring me a peach or pear so I have all fruits 😀&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
    likes: null,
    suggested_sort: null,
    banned_at_utc: null,
    view_count: null,
    archived: false,
    no_follow: false,
    is_crosspostable: false,
    pinned: false,
    over_18: false,
    all_awardings: [],
    awarders: [],
    media_only: false,
    link_flair_template_id: 'a1776686-72c8-11ea-8ffb-0eeaf353cc5f',
    can_gild: false,
    spoiler: false,
    locked: false,
    author_flair_text: null,
    treatment_tags: [],
    visited: false,
    removed_by: null,
    num_reports: null,
    distinguished: null,
    subreddit_id: 't5_2fvwbs',
    author_is_blocked: false,
    mod_reason_by: null,
    removal_reason: null,
    link_flair_background_color: '#0079d3',
    id: 'ta4829',
    is_robot_indexable: true,
    report_reasons: null,
    author: 'Yellano',
    discussion_type: null,
    num_comments: 10,
    send_replies: true,
    whitelist_status: 'all_ads',
    contest_mode: false,
    mod_reports: [],
    author_patreon_flair: false,
    author_flair_text_color: null,
    permalink: '/r/ACNHTurnips/comments/ta4829/nooks_selling_for_600_dm_for_code/',
    parent_whitelist_status: 'all_ads',
    stickied: false,
    url: 'https://www.reddit.com/r/ACNHTurnips/comments/ta4829/nooks_selling_for_600_dm_for_code/',
    subreddit_subscribers: 50205,
    created_utc: 1646818545,
    num_crossposts: 0,
    media: null,
    is_video: false,
  },

  {
    approved_at_utc: null,
    subreddit: 'ACNHTurnips',
    selftext: '',
    user_reports: [],
    saved: false,
    mod_reason_title: null,
    gilded: 0,
    clicked: false,
    title: '[Daisy] 93 Bells - Tips appreciated!',
    link_flair_richtext: [],
    subreddit_name_prefixed: 'r/ACNHTurnips',
    hidden: false,
    pwls: 6,
    link_flair_css_class: '',
    downs: 0,
    thumbnail_height: 140,
    top_awarded_type: null,
    hide_score: false,
    name: 't3_t8zo4w',
    quarantine: false,
    link_flair_text_color: 'light',
    upvote_ratio: 1,
    author_flair_background_color: null,
    subreddit_type: 'public',
    ups: 7,
    total_awards_received: 0,
    media_embed: {},
    thumbnail_width: 140,
    author_flair_template_id: null,
    is_original_content: false,
    author_fullname: 't2_69jp9bp7',
    secure_media: null,
    is_reddit_media_domain: true,
    is_meta: false,
    category: null,
    secure_media_embed: {},
    link_flair_text: 'Ended',
    can_mod_post: false,
    score: 7,
    approved_by: null,
    is_created_from_ads_ui: false,
    author_premium: false,
    thumbnail: 'https://b.thumbs.redditmedia.com/9CGCKhfMQmWpGeqVaCQUUP1lCRCKVkWZkBuTSzljHzc.jpg',
    edited: false,
    author_flair_css_class: null,
    author_flair_richtext: [],
    gildings: {},
    content_categories: null,
    is_self: false,
    mod_note: null,
    crosspost_parent_list: [
      {
        approved_at_utc: null,
        subreddit: 'AnimalCrossingNewHor',
        selftext: '[deleted]',
        user_reports: [],
        saved: false,
        mod_reason_title: null,
        gilded: 0,
        clicked: false,
        title:
          "Hosting Daisy. She's selling turnips for 93 Bells. Dodo: M33BH (More info in comments)",
        link_flair_richtext: [],
        subreddit_name_prefixed: 'r/AnimalCrossingNewHor',
        hidden: false,
        pwls: 6,
        link_flair_css_class: '',
        downs: 0,
        thumbnail_height: 140,
        top_awarded_type: null,
        hide_score: false,
        name: 't3_t8zkby',
        quarantine: false,
        link_flair_text_color: 'dark',
        upvote_ratio: 0.5,
        author_flair_background_color: '',
        subreddit_type: 'public',
        ups: 0,
        total_awards_received: 0,
        media_embed: {},
        thumbnail_width: 140,
        author_flair_template_id: null,
        is_original_content: false,
        secure_media: null,
        is_reddit_media_domain: true,
        is_meta: false,
        category: null,
        secure_media_embed: {},
        link_flair_text: 'Island Open',
        can_mod_post: false,
        score: 0,
        approved_by: null,
        is_created_from_ads_ui: false,
        thumbnail: 'default',
        edited: false,
        author_flair_css_class: null,
        gildings: {},
        content_categories: null,
        is_self: false,
        mod_note: null,
        created: 1646687374,
        link_flair_type: 'text',
        wls: 6,
        removed_by_category: 'deleted',
        banned_by: null,
        domain: 'i.redd.it',
        allow_live_comments: false,
        selftext_html:
          '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;[deleted]&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
        likes: null,
        suggested_sort: null,
        banned_at_utc: null,
        url_overridden_by_dest: 'https://i.redd.it/f0dtjggg11m81.jpg',
        view_count: null,
        archived: false,
        no_follow: true,
        is_crosspostable: false,
        pinned: false,
        over_18: false,
        all_awardings: [],
        awarders: [],
        media_only: false,
        link_flair_template_id: 'c347c98c-4d3b-11ec-a11c-96d0a1d11654',
        can_gild: false,
        spoiler: false,
        locked: false,
        author_flair_text: null,
        treatment_tags: [],
        visited: false,
        removed_by: null,
        num_reports: null,
        distinguished: null,
        subreddit_id: 't5_2eyuem',
        author_is_blocked: false,
        mod_reason_by: null,
        removal_reason: null,
        link_flair_background_color: '#ffb000',
        id: 't8zkby',
        is_robot_indexable: false,
        report_reasons: null,
        author: '[deleted]',
        discussion_type: null,
        num_comments: 2,
        send_replies: true,
        whitelist_status: 'all_ads',
        contest_mode: false,
        mod_reports: [],
        author_flair_text_color: 'dark',
        permalink:
          '/r/AnimalCrossingNewHor/comments/t8zkby/hosting_daisy_shes_selling_turnips_for_93_bells/',
        parent_whitelist_status: 'all_ads',
        stickied: false,
        url: 'https://i.redd.it/f0dtjggg11m81.jpg',
        subreddit_subscribers: 214331,
        created_utc: 1646687374,
        num_crossposts: 2,
        media: null,
        is_video: false,
      },
    ],
    created: 1646687658,
    link_flair_type: 'text',
    wls: 6,
    removed_by_category: null,
    banned_by: null,
    author_flair_type: 'text',
    domain: 'i.redd.it',
    allow_live_comments: false,
    selftext_html: null,
    likes: null,
    suggested_sort: null,
    banned_at_utc: null,
    url_overridden_by_dest: 'https://i.redd.it/f0dtjggg11m81.jpg',
    view_count: null,
    archived: false,
    no_follow: false,
    is_crosspostable: false,
    pinned: false,
    over_18: false,
    all_awardings: [],
    awarders: [],
    media_only: false,
    link_flair_template_id: 'aa7c035e-72c8-11ea-af84-0eea56f6d1f7',
    can_gild: false,
    spoiler: false,
    locked: false,
    author_flair_text: null,
    treatment_tags: [],
    visited: false,
    removed_by: null,
    num_reports: null,
    distinguished: null,
    subreddit_id: 't5_2fvwbs',
    author_is_blocked: false,
    mod_reason_by: null,
    removal_reason: null,
    link_flair_background_color: '#ea0027',
    id: 't8zo4w',
    is_robot_indexable: true,
    report_reasons: null,
    author: 'botanicalmagic',
    discussion_type: null,
    num_comments: 7,
    send_replies: false,
    whitelist_status: 'all_ads',
    contest_mode: false,
    mod_reports: [],
    author_patreon_flair: false,
    crosspost_parent: 't3_t8zkby',
    author_flair_text_color: null,
    permalink: '/r/ACNHTurnips/comments/t8zo4w/daisy_93_bells_tips_appreciated/',
    parent_whitelist_status: 'all_ads',
    stickied: false,
    url: 'https://i.redd.it/f0dtjggg11m81.jpg',
    subreddit_subscribers: 50205,
    created_utc: 1646687658,
    num_crossposts: 0,
    media: null,
    is_video: false,
  },
];
